### ISSUE TITLE
Improve pid command line handling

### ISSUE THREAD

**Issue by turlututututu** [ZXGuesser/pes2t42#1]
Hi! Let me start by saying that I enjoy your repo quite a lot :)

Regarding the pid in the script ts2pes.py, I think it would be better to document that the pid for -p must be in the hex representation (without the leading 0x) rather than its value expressed in base 10. Indeed many tools use the pid in it base 10 representation.

Or maybe parse the input and test wether it starts with '0x'

**Comment by ZXGuesser** [comment]
I intend to rewrite this into a single script that locates teletext streams and outputs them automatically, but the whole thing needs rewriting anyway to better handle missing packets and things.
For now I've added a note to the readme file
